apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerter
  labels:
    app: pipem.io
    component: alerter
    role: provider
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      component: alerter
  template:
    metadata:
      labels:
        app: pipem.io
        component: alerter
        role: provider
    spec:
      serviceAccountName: pipem-sa
      containers:
        - name: alerter
          image: {{ .Values.image }}:{{ .Values.version }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 30
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: pipem-config
          env:
            - name: 'MONGODB_URI'
              valueFrom:
                secretKeyRef:
                  name: pipem-secret
                  key: MONGODB_URI
